[WIP] Feat/associate bling order item with store
Purple-Stock/open-erp pull request #331
Opened 2023-10-28 22:48 UTC by gscarv13

2023-10-30 22:21 UTC, Pauloparakleto commented
Acredito que esta issue  #313 resolve esse problema.

2023-11-02 22:04 UTC, gscarv13 commented
> Acredito que esta issue #313 resolve esse problema.

Boa, valeu por avisar @Pauloparakleto  :]

2023-11-03 13:46 UTC, Pauloparakleto commented
Porfavor, fazer rebase com staging @gscarv13. Houve uma pequena mudança na ordem em que aparece os items na index.

2023-11-03 13:47 UTC, Pauloparakleto requested changes
Fazer rebase e resolver o conflito.

2023-11-03 13:50 UTC, Pauloparakleto commented on app/models/bling_order_item.rb
> +  def self.group_order_items(base_query)
Este me parece ser o método central que garante a ordem fixa dos items. Poderia providenciar o teste unitário a nível de model deste método?

2023-11-03 14:14 UTC, Pauloparakleto commented on spec/models/bling_order_item_spec.rb
> +    context 'when store has no BlingOrderItem' do
👏🏻 👏🏻 👏🏻

2023-11-03 16:38 UTC, gscarv13 commented on app/views/home/_order_items.html.erb
> +        <div class="card-body text-center">
Boa, adicionado.

2023-11-03 21:46 UTC, Pauloparakleto approved these changes

2023-11-03 21:47 UTC, merged