[/318] Exibe toastr quando ocorre falha no login
Purple-Stock/open-erp pull request #363
Opened 2023-11-08 15:22 UTC by gscarv13

## Solução proposta

No rails 7, o turbo precisa que seja feito um redirecionamento para funcionar corretamente. Para adequar o funcionamento atual ao que o tubo espera, seria necessário a criação de um controller customizado do `Devise` para  contornar o comportamento padrão.

Uma alternativa que dispença a necessidade de um `monkey patch` seria desligar o turbo para o formulário de login, e com isso permite que o toastr volte a funcionar corretamente em caso de falha no login por erros de email/senha

## Resultado

![image](https://github.com/Purple-Stock/open-erp/assets/71977763/5783fc52-20aa-49d5-81a2-4594ed1f067f)

2023-11-08 15:25 UTC, gscarv13 commented
@puppe1990 @Pauloparakleto Com essa mudança passamos a ter 2 avisos de falha ao tentar autenticar.

Seria válido remover o flash que esta acima do formulário, e manter apenas o toastr?

2023-11-08 16:08 UTC, Pauloparakleto commented
@gscarv13 It is a nice solution. Please,  provide the view test. I suggest using [capybara](https://github.com/teamcapybara/capybara#using-capybara-with-rspec). Check this example out.

2023-11-08 16:10 UTC, Pauloparakleto commented on app/views/devise/sessions/new.html.erb
> +    <%= form_for(resource, as: resource_name, url: session_path(resource_name), html: { class: 'needs-validation', 'data-turbo': 'false' }) do |f| %>
Please, add the view expectation [Capybara](https://github.com/teamcapybara/capybara#using-capybara-with-rspec). I think this is enought to keep it documented.

2023-11-08 16:11 UTC, Pauloparakleto requested changes
Please, add the view expectation [Capybara](https://github.com/teamcapybara/capybara#using-capybara-with-rspec). I think this is enought to keep it documented.

2023-11-17 21:37 UTC, Pauloparakleto commented
> @puppe1990 @Pauloparakleto Com essa mudança passamos a ter 2 avisos de falha ao tentar autenticar.
> 
> Seria válido remover o flash que esta acima do formulário, e manter apenas o toastr?

Por mim, mantem-se o aviso acima do formulário, uma vez que o aviso no canto superior direito desaparece.
Desculpe pela demora em responder @gscarv13

2023-11-21 13:03 UTC, Pauloparakleto approved these changes
Com estes testes, fica provado que o aviso voltou a funcionar em caso de falha no login.
@puppe1990 
@gscarv13 thanks for your contribution!

2023-11-21 13:03 UTC, merged